Handle base path
MilanKovacic/vite-plugin-externalize-dependencies pull request #111
Opened 2024-07-22 20:38 UTC by Vija02

This PR adds support for projects that uses the `base` setting. We simply modify the RegExp and add the path to the match pattern.

This fix is also described in this comment here:
https://github.com/vitejs/vite/issues/6582#issuecomment-2112466813

2024-07-22 23:15 UTC, webJose commented
Interesting.  Coincidentally, someone showed up at my plug-in's Discussions section ([here](https://github.com/WJSoftware/vite-plugin-single-spa/discussions/170)) and I recommended him to come to this repository and file a bug for the cases where a base was used, so thumbs up for this PR from me, a random guy. 😃

2024-07-22 23:38 UTC, MilanKovacic requested changes
Thank you for the PR. I was able to reproduce the issue. Can you please add a changeset? You can bump the major version so 1.0.0 is released, since plugin has been available for some time with a stable API.

2024-07-22 23:38 UTC, MilanKovacic commented on src/index.ts
> +const modulePrefixTransform = ({ base }: { base: string }): Plugin => ({
Can you modify the TSDoc to include the base parameter description?

2024-07-23 17:07 UTC, Vija02 commented
Done both 👍🏻  @MilanKovacic

2024-07-23 23:36 UTC, MilanKovacic approved these changes, later dismissed

2024-07-23 23:41 UTC, MilanKovacic commented
@Vija02 Can you please just run "prettier:fix" script? I will make sure to improve the development experience by automating it via hooks.

2024-07-24 01:26 UTC, Vija02 commented
Sorry about that! Done

2024-07-24 01:56 UTC, MilanKovacic approved these changes

2024-07-24 01:56 UTC, merged